site_name: Jarvis-HEP Documentation
site_url: https://pengxuan-zhu-phys.github.io/Jarvis-Docs/

theme:
  name: material
  logo: assets/JarvisHEP.png
  favicon: assets/JarvisHEP.png
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search

nav:
  - Home: index.md
  - Get Start:
      - Eggbox (Start Here): tutorial/eggbox.md
  - Documentations:
      - Background & References:
          - YAML Format introduction: yaml/yaml_introduction.md
      - Calculator Contract: core/calculator_contract.md
  - Jarvis-HEP:
      - Overview: jarvis-hep/overview.md
  - JarvisPLOT:
      - Overview: jarvisplot/overview.md